### ISSUE TITLE
cannot run

### ISSUE THREAD

**Issue by i-Taozi** [muremwa/VSmarketplace-scrapper#1]
```Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1257, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1303, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1252, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1012, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 952, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1426, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hujunhao/Code/Py/pluginCrawler.py", line 83, in <module>
    details = vscrap.get_extension_details('muremwa.read-urls')
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/vscrap/_sc.py", line 14, in rap
    page_text = _retrieve_extension_page(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/vscrap/_scrap.py", line 56, in _retrieve_extension_page
    page = request.urlopen(url)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)>

Process finished with exit code 1
```

When I run :
```
import vscrap
details = vscrap.get_extension_details('muremwa.read-urls')
```

**Comment by i-Taozi** [comment]
And is there any way to get Extension's url, like https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker

**Comment by muremwa** [comment]
> ```
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1346, in do_open
>     h.request(req.get_method(), req.selector, req.data, headers,
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1257, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1303, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1252, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1012, in _send_output
>     self.send(msg)
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 952, in send
>     self.connect()
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1426, in connect
>     self.sock = self._context.wrap_socket(self.sock,
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
>     return self.sslsocket_class._create(
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
>     self.do_handshake()
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
>     self._sslobj.do_handshake()
> ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/hujunhao/Code/Py/pluginCrawler.py", line 83, in <module>
>     details = vscrap.get_extension_details('muremwa.read-urls')
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/vscrap/_sc.py", line 14, in rap
>     page_text = _retrieve_extension_page(
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/vscrap/_scrap.py", line 56, in _retrieve_extension_page
>     page = request.urlopen(url)
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
>     return opener.open(url, data, timeout)
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 517, in open
>     response = self._open(req, data)
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 534, in _open
>     result = self._call_chain(self.handle_open, protocol, protocol +
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
>     result = func(*args)
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1389, in https_open
>     return self.do_open(http.client.HTTPSConnection, req,
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1349, in do_open
>     raise URLError(err)
> urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)>
> 
> Process finished with exit code 1
> ```
> 
> When I run :
> 
> ```
> import vscrap
> details = vscrap.get_extension_details('muremwa.read-urls')
> ```


Sorry, I'm only seeing this issue now @i-Taozi 

The issue could have been local to your environment. It runs fine on mine and a few others I've tested. Freshly installed.
![image](https://github.com/muremwa/VSmarketplace-scrapper/assets/29689519/22185128-f9b5-4c9e-9a96-cde4d6e01118)

[This question on StackOverflow](https://stackoverflow.com/questions/50236117/scraping-ssl-certificate-verify-failed-error-for-http-en-wikipedia-org, "[Scraping: SSL: CERTIFICATE_VERIFY_FAILED error for http://en.wikipedia.org](https://stackoverflow.com/questions/50236117/scraping-ssl-certificate-verify-failed-error-for-http-en-wikipedia-org)") could help.

**Comment by muremwa** [comment]
> And is there any way to get Extension's url, like https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker

That's not part of the return details but it can be added.
